# Generated by Django 2.0.2 on 2018-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationcommon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='model_pk',
            field=models.CharField(max_length=255),
        ),
    ]
